"""initial live data platform

Revision ID: 1a36959a7f7b
Revises:
Create Date: 2026-08-26 21:05:05.098978
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1a36959a7f7b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authority_identifiers",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=200), nullable=False),
        sa.Column("scheme", sa.String(length=80), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("is_authoritative", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authority_identifiers")),
        sa.UniqueConstraint(
            "scheme", "value", name=op.f("uq_authority_identifiers_scheme")
        ),
    )
    op.create_index(
        "ix_authority_entity",
        "authority_identifiers",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authority_identifiers_entity_id"),
        "authority_identifiers",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authority_identifiers_entity_type"),
        "authority_identifiers",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authority_identifiers_scheme"),
        "authority_identifiers",
        ["scheme"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authority_identifiers_value"),
        "authority_identifiers",
        ["value"],
        unique=False,
    )
    op.create_table(
        "entity_search_terms",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=200), nullable=False),
        sa.Column("term", sa.String(length=500), nullable=False),
        sa.Column("normalized_term", sa.String(length=500), nullable=False),
        sa.Column("match_method", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_search_terms")),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "match_method",
            "normalized_term",
            name=op.f("uq_entity_search_terms_entity_type"),
        ),
    )
    op.create_index(
        "ix_entity_search_term_lookup",
        "entity_search_terms",
        ["normalized_term", "entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_search_terms_entity_id"),
        "entity_search_terms",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_search_terms_entity_type"),
        "entity_search_terms",
        ["entity_type"],
        unique=False,
    )
    op.create_table(
        "countries",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("iso_alpha3", sa.String(length=3), nullable=False),
        sa.Column("iso_alpha2", sa.String(length=2), nullable=True),
        sa.Column("iso_numeric", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("region", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
        sa.UniqueConstraint("iso_alpha2", name=op.f("uq_countries_iso_alpha2")),
        sa.UniqueConstraint("iso_alpha3", name=op.f("uq_countries_iso_alpha3")),
        sa.UniqueConstraint("iso_numeric", name=op.f("uq_countries_iso_numeric")),
    )
    op.create_table(
        "dataset_state",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("dataset_kind", sa.String(length=80), nullable=False),
        sa.Column("period", sa.String(length=40), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latest_update_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source_snapshot_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("update_sequence", sa.Integer(), nullable=False),
        sa.Column("disclaimer", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_state")),
    )
    op.create_table(
        "dataset_updates",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("update_mode", sa.String(length=40), nullable=False),
        sa.Column(
            "source_snapshot_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("previous_dataset_version", sa.String(length=120), nullable=True),
        sa.Column("dataset_version", sa.String(length=120), nullable=False),
        sa.Column("resolver_version", sa.String(length=120), nullable=False),
        sa.Column("metric_calculation_version", sa.String(length=120), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "affected_entities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_updates")),
    )
    op.create_table(
        "external_resources",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=200), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=160), nullable=False),
        sa.Column("source_record_id", sa.String(length=400), nullable=True),
        sa.Column(
            "external_id",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_method", sa.String(length=120), nullable=True),
        sa.Column("health_status", sa.String(length=40), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("redirect_target", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_resources")),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "resource_type",
            "url",
            name=op.f("uq_external_resources_entity_type"),
        ),
    )
    op.create_index(
        op.f("ix_external_resources_entity_id"),
        "external_resources",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_resources_entity_type"),
        "external_resources",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_resources_health_status"),
        "external_resources",
        ["health_status"],
        unique=False,
    )
    op.create_table(
        "metric_definitions",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("category", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("interpretation", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column(
            "required_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("implementation_status", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_definitions")),
    )
    op.create_table(
        "papers",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("publication_year", sa.Integer(), nullable=False),
        sa.Column("doi", sa.String(length=500), nullable=True),
        sa.Column("arxiv_id", sa.String(length=100), nullable=True),
        sa.Column(
            "external_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_papers")),
    )
    op.create_index(op.f("ix_papers_arxiv_id"), "papers", ["arxiv_id"], unique=True)
    op.create_index(op.f("ix_papers_doi"), "papers", ["doi"], unique=True)
    op.create_index(
        op.f("ix_papers_publication_year"), "papers", ["publication_year"], unique=False
    )
    op.create_table(
        "researchers",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column(
            "aliases",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "historical_names",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "external_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("identity_confidence", sa.Float(), nullable=True),
        sa.Column(
            "field_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_researchers")),
    )
    op.create_index(
        op.f("ix_researchers_canonical_name"),
        "researchers",
        ["canonical_name"],
        unique=False,
    )
    op.create_table(
        "science_domains",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_science_domains")),
    )
    op.create_table(
        "source_cursors",
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column(
            "checkpoint",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_source_cursors")),
    )
    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("source_version", sa.String(length=120), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("update_mode", sa.String(length=40), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("previous_snapshot_id", sa.String(length=240), nullable=True),
        sa.Column("content_checksum", sa.String(length=128), nullable=False),
        sa.Column("storage_reference", sa.Text(), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["previous_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_source_snapshots_previous_snapshot_id_source_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
        sa.UniqueConstraint(
            "source", "content_checksum", name=op.f("uq_source_snapshots_source")
        ),
    )
    op.create_index(
        op.f("ix_source_snapshots_source"), "source_snapshots", ["source"], unique=False
    )
    op.create_table(
        "update_runs",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor_before", sa.Text(), nullable=True),
        sa.Column("cursor_after", sa.Text(), nullable=True),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_added", sa.Integer(), nullable=False),
        sa.Column("records_changed", sa.Integer(), nullable=False),
        sa.Column("records_unresolved", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column(
            "affected_entities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "affected_metric_partitions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_update_runs")),
    )
    op.create_index(
        op.f("ix_update_runs_source"), "update_runs", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_update_runs_status"), "update_runs", ["status"], unique=False
    )
    op.create_table(
        "authorships",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("paper_id", sa.String(length=200), nullable=False),
        sa.Column("researcher_id", sa.String(length=160), nullable=False),
        sa.Column("author_position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "author_position > 0", name=op.f("ck_authorships_authorship_position")
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_authorships_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["researchers.id"],
            name=op.f("fk_authorships_researcher_id_researchers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authorships")),
        sa.UniqueConstraint(
            "paper_id", "researcher_id", name=op.f("uq_authorships_paper_id")
        ),
    )
    op.create_index(
        op.f("ix_authorships_paper_id"), "authorships", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_authorships_researcher_id"),
        "authorships",
        ["researcher_id"],
        unique=False,
    )
    op.create_table(
        "citations",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("citing_paper_id", sa.String(length=200), nullable=False),
        sa.Column("cited_paper_id", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("source_record_id", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cited_paper_id"],
            ["papers.id"],
            name=op.f("fk_citations_cited_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["citing_paper_id"],
            ["papers.id"],
            name=op.f("fk_citations_citing_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citations")),
        sa.UniqueConstraint(
            "citing_paper_id",
            "cited_paper_id",
            "source",
            name=op.f("uq_citations_citing_paper_id"),
        ),
    )
    op.create_index(
        op.f("ix_citations_cited_paper_id"),
        "citations",
        ["cited_paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citations_citing_paper_id"),
        "citations",
        ["citing_paper_id"],
        unique=False,
    )
    op.create_table(
        "geographic_views",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("country_id", sa.String(length=120), nullable=False),
        sa.Column(
            "geometry_iso_numerics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "location_country_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_geographic_views_country_id_countries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geographic_views")),
    )
    op.create_index(
        op.f("ix_geographic_views_country_id"),
        "geographic_views",
        ["country_id"],
        unique=True,
    )
    op.create_table(
        "institutions",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column(
            "aliases",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "historical_names",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "external_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("identity_confidence", sa.Float(), nullable=True),
        sa.Column("country_id", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=240), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column(
            "field_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name=op.f("ck_institutions_institution_latitude"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name=op.f("ck_institutions_institution_longitude"),
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_institutions_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutions")),
    )
    op.create_index(
        op.f("ix_institutions_canonical_name"),
        "institutions",
        ["canonical_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutions_country_id"), "institutions", ["country_id"], unique=False
    )
    op.create_table(
        "metric_observations",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=200), nullable=False),
        sa.Column("science_domain_id", sa.String(length=120), nullable=True),
        sa.Column("field_id", sa.String(length=120), nullable=True),
        sa.Column("metric_id", sa.String(length=160), nullable=False),
        sa.Column("period", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=240), nullable=False),
        sa.Column("algorithm_version", sa.String(length=120), nullable=False),
        sa.Column("calculation_version", sa.String(length=120), nullable=False),
        sa.Column("data_source_version", sa.String(length=160), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["metric_definitions.id"],
            name=op.f("fk_metric_observations_metric_id_metric_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_observations")),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "science_domain_id",
            "field_id",
            "metric_id",
            "period",
            "calculation_version",
            name=op.f("uq_metric_observations_entity_type"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_metric_observation_partition",
        "metric_observations",
        ["metric_id", "field_id", "period", "entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_entity_id"),
        "metric_observations",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_entity_type"),
        "metric_observations",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_field_id"),
        "metric_observations",
        ["field_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_metric_id"),
        "metric_observations",
        ["metric_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_period"),
        "metric_observations",
        ["period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_science_domain_id"),
        "metric_observations",
        ["science_domain_id"],
        unique=False,
    )
    op.create_table(
        "raw_entity_records",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("source_record_id", sa.String(length=400), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=240), nullable=False),
        sa.Column("raw_name", sa.Text(), nullable=False),
        sa.Column(
            "external_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_raw_entity_records_source_snapshot_id_source_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_entity_records")),
        sa.UniqueConstraint(
            "source",
            "source_record_id",
            "source_snapshot_id",
            name=op.f("uq_raw_entity_records_source"),
        ),
    )
    op.create_index(
        op.f("ix_raw_entity_records_entity_type"),
        "raw_entity_records",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_entity_records_source"),
        "raw_entity_records",
        ["source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_entity_records_source_snapshot_id"),
        "raw_entity_records",
        ["source_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "research_fields",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("domain_id", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "provider_mappings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["science_domains.id"],
            name=op.f("fk_research_fields_domain_id_science_domains"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_fields")),
    )
    op.create_index(
        op.f("ix_research_fields_domain_id"),
        "research_fields",
        ["domain_id"],
        unique=False,
    )
    op.create_table(
        "resource_checks",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("resource_id", sa.String(length=240), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("redirect_target", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["external_resources.id"],
            name=op.f("fk_resource_checks_resource_id_external_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_checks")),
    )
    op.create_index(
        op.f("ix_resource_checks_resource_id"),
        "resource_checks",
        ["resource_id"],
        unique=False,
    )
    op.create_table(
        "historical_events",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.String(length=120), nullable=False),
        sa.Column(
            "related_researcher_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "related_institution_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["research_fields.id"],
            name=op.f("fk_historical_events_field_id_research_fields"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_events")),
    )
    op.create_index(
        op.f("ix_historical_events_field_id"),
        "historical_events",
        ["field_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_events_year"), "historical_events", ["year"], unique=False
    )
    op.create_table(
        "identity_resolutions",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("raw_entity_record_id", sa.String(length=240), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("canonical_entity_id", sa.String(length=200), nullable=True),
        sa.Column("method", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("resolver_version", sa.String(length=120), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_entity_record_id"],
            ["raw_entity_records.id"],
            name=op.f(
                "fk_identity_resolutions_raw_entity_record_id_raw_entity_records"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_resolutions")),
    )
    op.create_index(
        op.f("ix_identity_resolutions_canonical_entity_id"),
        "identity_resolutions",
        ["canonical_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_resolutions_raw_entity_record_id"),
        "identity_resolutions",
        ["raw_entity_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_resolutions_status"),
        "identity_resolutions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "paper_fields",
        sa.Column("paper_id", sa.String(length=200), nullable=False),
        sa.Column("field_id", sa.String(length=120), nullable=False),
        sa.Column("classification_method", sa.String(length=120), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["research_fields.id"],
            name=op.f("fk_paper_fields_field_id_research_fields"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_paper_fields_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("paper_id", "field_id", name=op.f("pk_paper_fields")),
    )
    op.create_table(
        "research_groups",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("institution_id", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "field_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_research_groups_institution_id_institutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_groups")),
    )
    op.create_index(
        op.f("ix_research_groups_institution_id"),
        "research_groups",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_groups_name"), "research_groups", ["name"], unique=False
    )
    op.create_table(
        "affiliations",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("researcher_id", sa.String(length=160), nullable=False),
        sa.Column("institution_id", sa.String(length=160), nullable=False),
        sa.Column("research_group_id", sa.String(length=160), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_affiliations_affiliation_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_affiliations_institution_id_institutions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["research_group_id"],
            ["research_groups.id"],
            name=op.f("fk_affiliations_research_group_id_research_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["researchers.id"],
            name=op.f("fk_affiliations_researcher_id_researchers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliations")),
    )
    op.create_index(
        op.f("ix_affiliations_institution_id"),
        "affiliations",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_affiliations_research_group_id"),
        "affiliations",
        ["research_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_affiliations_researcher_id"),
        "affiliations",
        ["researcher_id"],
        unique=False,
    )
    op.create_table(
        "identity_reviews",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("resolution_id", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "candidate_entity_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("decision_entity_id", sa.String(length=200), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=240), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["identity_resolutions.id"],
            name=op.f("fk_identity_reviews_resolution_id_identity_resolutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_reviews")),
        sa.UniqueConstraint(
            "resolution_id", name=op.f("uq_identity_reviews_resolution_id")
        ),
    )
    op.create_index(
        op.f("ix_identity_reviews_status"), "identity_reviews", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_identity_reviews_status"), table_name="identity_reviews")
    op.drop_table("identity_reviews")
    op.drop_index(op.f("ix_affiliations_researcher_id"), table_name="affiliations")
    op.drop_index(op.f("ix_affiliations_research_group_id"), table_name="affiliations")
    op.drop_index(op.f("ix_affiliations_institution_id"), table_name="affiliations")
    op.drop_table("affiliations")
    op.drop_index(op.f("ix_research_groups_name"), table_name="research_groups")
    op.drop_index(
        op.f("ix_research_groups_institution_id"), table_name="research_groups"
    )
    op.drop_table("research_groups")
    op.drop_table("paper_fields")
    op.drop_index(
        op.f("ix_identity_resolutions_status"), table_name="identity_resolutions"
    )
    op.drop_index(
        op.f("ix_identity_resolutions_raw_entity_record_id"),
        table_name="identity_resolutions",
    )
    op.drop_index(
        op.f("ix_identity_resolutions_canonical_entity_id"),
        table_name="identity_resolutions",
    )
    op.drop_table("identity_resolutions")
    op.drop_index(op.f("ix_historical_events_year"), table_name="historical_events")
    op.drop_index(op.f("ix_historical_events_field_id"), table_name="historical_events")
    op.drop_table("historical_events")
    op.drop_index(op.f("ix_resource_checks_resource_id"), table_name="resource_checks")
    op.drop_table("resource_checks")
    op.drop_index(op.f("ix_research_fields_domain_id"), table_name="research_fields")
    op.drop_table("research_fields")
    op.drop_index(
        op.f("ix_raw_entity_records_source_snapshot_id"),
        table_name="raw_entity_records",
    )
    op.drop_index(op.f("ix_raw_entity_records_source"), table_name="raw_entity_records")
    op.drop_index(
        op.f("ix_raw_entity_records_entity_type"), table_name="raw_entity_records"
    )
    op.drop_table("raw_entity_records")
    op.drop_index(
        op.f("ix_metric_observations_science_domain_id"),
        table_name="metric_observations",
    )
    op.drop_index(
        op.f("ix_metric_observations_period"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_metric_id"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_field_id"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_entity_type"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_entity_id"), table_name="metric_observations"
    )
    op.drop_index("ix_metric_observation_partition", table_name="metric_observations")
    op.drop_table("metric_observations")
    op.drop_index(op.f("ix_institutions_country_id"), table_name="institutions")
    op.drop_index(op.f("ix_institutions_canonical_name"), table_name="institutions")
    op.drop_table("institutions")
    op.drop_index(op.f("ix_geographic_views_country_id"), table_name="geographic_views")
    op.drop_table("geographic_views")
    op.drop_index(op.f("ix_citations_citing_paper_id"), table_name="citations")
    op.drop_index(op.f("ix_citations_cited_paper_id"), table_name="citations")
    op.drop_table("citations")
    op.drop_index(op.f("ix_authorships_researcher_id"), table_name="authorships")
    op.drop_index(op.f("ix_authorships_paper_id"), table_name="authorships")
    op.drop_table("authorships")
    op.drop_index(op.f("ix_update_runs_status"), table_name="update_runs")
    op.drop_index(op.f("ix_update_runs_source"), table_name="update_runs")
    op.drop_table("update_runs")
    op.drop_index(op.f("ix_source_snapshots_source"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_table("source_cursors")
    op.drop_table("science_domains")
    op.drop_index(op.f("ix_researchers_canonical_name"), table_name="researchers")
    op.drop_table("researchers")
    op.drop_index(op.f("ix_papers_publication_year"), table_name="papers")
    op.drop_index(op.f("ix_papers_doi"), table_name="papers")
    op.drop_index(op.f("ix_papers_arxiv_id"), table_name="papers")
    op.drop_table("papers")
    op.drop_table("metric_definitions")
    op.drop_index(
        op.f("ix_external_resources_health_status"), table_name="external_resources"
    )
    op.drop_index(
        op.f("ix_external_resources_entity_type"), table_name="external_resources"
    )
    op.drop_index(
        op.f("ix_external_resources_entity_id"), table_name="external_resources"
    )
    op.drop_table("external_resources")
    op.drop_table("dataset_updates")
    op.drop_table("dataset_state")
    op.drop_table("countries")
    op.drop_index(
        op.f("ix_entity_search_terms_entity_type"),
        table_name="entity_search_terms",
    )
    op.drop_index(
        op.f("ix_entity_search_terms_entity_id"),
        table_name="entity_search_terms",
    )
    op.drop_index("ix_entity_search_term_lookup", table_name="entity_search_terms")
    op.drop_table("entity_search_terms")
    op.drop_index(
        op.f("ix_authority_identifiers_value"), table_name="authority_identifiers"
    )
    op.drop_index(
        op.f("ix_authority_identifiers_scheme"), table_name="authority_identifiers"
    )
    op.drop_index(
        op.f("ix_authority_identifiers_entity_type"), table_name="authority_identifiers"
    )
    op.drop_index(
        op.f("ix_authority_identifiers_entity_id"), table_name="authority_identifiers"
    )
    op.drop_index("ix_authority_entity", table_name="authority_identifiers")
    op.drop_table("authority_identifiers")
    # ### end Alembic commands ###
