"""Canonical Atlas Physicus field ontology and provider mapping."""

from .mapping import (
    ARXIV_CATEGORY_TAXONOMY,
    CROSS_PROVIDER_FIELD_RECONCILIATION_VERSION,
    CROSSREF_SUBJECT_TAXONOMY,
    FIELD_WEIGHTING_POLICY_VERSION,
    INSPIRE_CATEGORY_TAXONOMY,
    PROVIDER_FIELD_MAPPING_RULES_V1,
    PROVIDER_FIELD_MAPPING_VERSION,
    AtlasFieldAssignment,
    CategoryMapping,
    CrossProviderFieldLedger,
    FieldMappingResult,
    FieldMappingRule,
    Provider,
    ProviderCategoryEvidence,
    ProviderCategoryRole,
    ProviderFieldProjection,
    ReconciledCategoryMapping,
    map_provider_categories,
    reconcile_cross_provider_field_evidence,
)
from .ontology import (
    PHYSICS_DOMAIN_ID,
    PHYSICS_FIELD_DEFINITIONS_V1,
    PHYSICS_FIELD_ONTOLOGY_PROVENANCE,
    PHYSICS_FIELD_ONTOLOGY_V1,
    PHYSICS_FIELD_ONTOLOGY_VERSION,
    FieldDefinition,
    FieldOntologyProvenance,
    PhysicsFieldOntology,
)

__all__ = [
    "ARXIV_CATEGORY_TAXONOMY",
    "CROSS_PROVIDER_FIELD_RECONCILIATION_VERSION",
    "CROSSREF_SUBJECT_TAXONOMY",
    "FIELD_WEIGHTING_POLICY_VERSION",
    "INSPIRE_CATEGORY_TAXONOMY",
    "PHYSICS_DOMAIN_ID",
    "PHYSICS_FIELD_DEFINITIONS_V1",
    "PHYSICS_FIELD_ONTOLOGY_PROVENANCE",
    "PHYSICS_FIELD_ONTOLOGY_V1",
    "PHYSICS_FIELD_ONTOLOGY_VERSION",
    "PROVIDER_FIELD_MAPPING_RULES_V1",
    "PROVIDER_FIELD_MAPPING_VERSION",
    "AtlasFieldAssignment",
    "CategoryMapping",
    "CrossProviderFieldLedger",
    "FieldDefinition",
    "FieldMappingResult",
    "FieldMappingRule",
    "FieldOntologyProvenance",
    "PhysicsFieldOntology",
    "Provider",
    "ProviderCategoryEvidence",
    "ProviderCategoryRole",
    "ProviderFieldProjection",
    "ReconciledCategoryMapping",
    "map_provider_categories",
    "reconcile_cross_provider_field_evidence",
]
